

networks:
  dev:
    driver: bridge

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    depends_on:
    - frontend
    - backend
    restart: always
    ports:
      - "80:80"
    volumes: 
      - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf
    networks:
      - dev

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: dev-backend
    container_name: dev_backend
    env_file: 
      - ./backend/.env
    ports:
      - "5000:5000"
    tty: true
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - dev

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    image: dev-client
    container_name: dev_client
    env_file: 
      - ./frontend/.env
    ports:
      - "5173:5173"
    tty: true
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - dev